[package]
name = "water-sensor-firmware"
version = "0.1.9"
authors = ["Raphael Nestler <raphael.nestler@gmail.com>"]
description = "Firmware for the Credump water-sensor project"
keywords = ["arm", "cortex-m"]
categories = ["embedded", "no-std"]
license = "GPL-3.0"
repository = "https://github.com/coredump-ch/water-sensor-firmware-rs"
[profile.dev]
codegen-units = 1

[profile.release]
lto = true
debug = true

[dependencies]
cortex-m = "0.2.7"
cortex-m-rt = "0.2.3"
lpc11uxx = { git = "https://github.com/coredump-ch/lpc11uxx-rs" }
