version: 2

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - fmt

jobs:
  build:
    docker:
      - image: rust:1.43.0
    environment:
      # https://github.com/rust-lang/cargo/issues/2078
      CARGO_NET_GIT_FETCH_WITH_CLI: "true"
    steps:
      - checkout
      - run: apt update -y
      - run: apt install -y gcc-arm-none-eabi
      - run: rustup target add thumbv6m-none-eabi
      - run: cargo build --release --bins --examples
      - run: cargo build --release --bins --examples --features dev
      - run: cargo test --target x86_64-unknown-linux-gnu --tests
      - run: cargo test --target x86_64-unknown-linux-gnu --tests --features dev

  fmt:
    docker:
      - image: rust:1.43.0
    steps:
      - checkout
      - run: rustup component add rustfmt
      - run: cargo fmt -- --check
