version: 2

jobs:
  build:
    docker:
      - image: rust:1.32.0
    steps:
      - checkout
      - run: apt update -y
      - run: apt install -y gcc-arm-none-eabi
      - run: rustup target add thumbv6m-none-eabi
      - run: cargo build --release
