version: 2

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - fmt

jobs:
  build:
    docker:
      - image: rust:1.50.0
    environment:
      # https://github.com/rust-lang/cargo/issues/2078
      CARGO_NET_GIT_FETCH_WITH_CLI: "true"
    steps:
      - checkout
      - run: apt update -y
      - run: apt install -y gcc-arm-none-eabi libusb-1.0-0-dev
      - run: rustup target add thumbv6m-none-eabi
      # Test config
      - run: cd config && cargo test --target x86_64-unknown-linux-gnu
      # Build firmware (ARM)
      - run: cd firmware && cargo build --release --bins --examples
      - run: cd firmware && cargo build --release --bins --examples --features dev
      # Test firmware (x86_64)
      - run: cd firmware && cargo test --target x86_64-unknown-linux-gnu --tests
      - run: cd firmware && cargo test --target x86_64-unknown-linux-gnu --tests --features dev
      # Test config-flasher (x86_64)
      - run: cd config-flasher && cargo test --target x86_64-unknown-linux-gnu

  fmt:
    docker:
      - image: rust:1.50.0
    steps:
      - checkout
      - run: rustup component add rustfmt
      - run: cd firmware && cargo fmt -- --check
      - run: cd config && cargo fmt -- --check
      - run: cd config-flasher && cargo fmt -- --check
