version: 2

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - fmt

jobs:
  build:
    docker:
      - image: rust:1.40.0
    environment:
      GFROERLI_APP_EUI: "0011223344556677"
      GFROERLI_APP_KEY: "0011223344556677889900aabbccddee"
    steps:
      - checkout
      - run: apt update -y
      - run: apt install -y gcc-arm-none-eabi
      - run: rustup target add thumbv6m-none-eabi
      - run: cargo build --release

  fmt:
    docker:
      - image: rust:1.40.0
    steps:
      - checkout
      - run: rustup component add rustfmt
      - run: cargo fmt -- --check
